### ISSUE TITLE
Seria possível disponibilizar um código para raspberry?

### ISSUE THREAD

**Issue by knowdbtech** [MSS-ELETRONICA/DM02A#1]
Seria possível disponibilizar um código para raspberry?

Pq neste como ele importa uma biblioteca do arduino e não uma da GPIO do raspberry não consigo fazer funcionar no raspberry.

**Comment by MSS-ELETRONICA** [comment]
Olá, eu não tenho raspberry e não sei programar ele. Você pode tentar implementar seu próprio código sem a biblioteca, pois as funções são simples. Para acionar um nível, tem que deixar o pino em nível baixo por um tempo que corresponde ao nível, sendo 500uS para cada nível, então uma função de delay já serve. Para o feedback, tem que colocar o pino em nível baixo por 40mS a 50mS e depois mudar esse pino para entrada e ler o tempo que o módulo fez o pino ficar em nível baixo, sendo novamente 500uS para cada nível,

Poderá olhar as bibliotecas para Arduino e escrever a sua, são bem simples,

Veja o manual do produto sobre isso no link (https://www.msseletronica.com/arquivos/DM02A.pdf),

Att Misael

**Comment by knowdbtech** [comment]
Consegui, como posso te enviar o código? porque quando as pessoas procuram por dimmer, sempre é só pra arduino ou esp, fiz um script bem simples em python que roda no raspberry. Posso te enviar e você publica igual ao do arduino. Assim você amplia o público alvo, vendendo a placa também para quem tem raspberry.

**Comment by MSS-ELETRONICA** [comment]
me mande por email e me informe o nome para eu informar a autoria. Email: msseletronica@hotmail.com.br

Obrigado.

Att Misael

**Comment by knowdbtech** [comment]
Enviado, o codigo é simple, porém só fiz o de envio de sinal, o feedback não consegui simular a função pulsein do arduino.

bastar chamar da seguinte forma:

`python dimmer_envia_nivel_dm02a.py 35` (35 eh o valor que vai para dimmer sendo entre 0 e 70

É isso, para o meu caso já resolveu, eu posso guardar o valor que foi enviado em algum lugar para não precisar ler o feedback.

Pode associar essa conta minha como autor!

Obrigado e até mais!

**Comment by MSS-ELETRONICA** [comment]
Entendi,

No caso do 'pulsein' teria que usar alguma alguma função que conte tempo. Aguardar o pino mudar de nível lógico, quando mudar zerar um contador de tempo, ficar em loop até o pino voltar ao nível alto, ler o contador de tempo,

Ainda essa semana vou subir o código que me enviou, obrigado,

Att Misael
